### ISSUE TITLE
Java开发工程师进阶书单 | Leeyom的个人站

### ISSUE THREAD

**Issue by wangleeyom** [wangleeyom/wangleeyom.github.io#71]
http://leeyom.top/2017/10/15/tech-java-book-list/

**Comment by SOBIGUFO** [comment]
After doing more than a year of development, I feel that I have been staying in the level will only use, but to get to the core of a technology principle, they can not answer. Each programmer is written from the simplest CRUD, but when the simple business logic code is written, it will make people fall into a numb state and make people feel at home. How can we get out of this vicious circle, so that they become a qualified programmer? Books are the best spiritual food of mankind, programmers in addition to writing code, should also stop and read more technical related books. This will help us to understand a deeper level of knowledge. Here I myself from the Internet to collect some of the advanced books developed by Java, are high-definition pdf documents, the focus is a bookmark directory, easy to locate access. I have uploaded the document to Baidu cloud, if the economy allows, you can buy paper entities to support the original author.

**Comment by wangleeyom** [comment]
@SOBIGUFO 还帮我翻译了啊，可以的。

**Comment by Chakid** [comment]
博客又变帅了，哈哈~~~~

**Comment by wangleeyom** [comment]
@Chakid 是的哈，换了个酷酷的主题，哈哈！

**Comment by a1260157543** [comment]
博客逼格高了 每天让自己进步一点 加油！

**Comment by wangleeyom** [comment]
@a1260157543 哈哈，常来看看。
